<?php
get_header();
$img = get_template_directory_uri() . '/assets/images/';
?>
<main class="site-main">
<section class="hero hero-home"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">جراحی زیبایی پیشرفته</span><h1>زیبایی طبیعی، اعتماد بیشتر، نتیجه‌ای پایدار.</h1><p>کلینیک ما با تیم متخصص و فناوری روز، خدمات جراحی و غیرجراحی زیبایی را با دقت بالا و نتیجه‌ای طبیعی ارائه می‌دهد.</p><div class="hero-actions"><a href="#contact" class="button">رزرو مشاوره</a><a href="#services" class="button button-secondary">مشاهده خدمات</a></div><ul class="hero-points"><li>بیش از ۱۵ سال تجربه</li><li>تیم جراحان متخصص</li><li>نتایج طبیعی و ایمن</li></ul></div><div class="hero-visual"><div class="hero-card card-main"><img src="<?php echo esc_url($img . 'hero-clinic.svg'); ?>" alt="تصویر نمونه کلینیک جراحی زیبایی"></div><div class="hero-badge badge-1">۴.۹/۵ امتیاز</div><div class="hero-badge badge-2">+۱۲,۰۰۰ بیمار</div></div></div></section>
<section class="section stats-section"><div class="container stats-grid"><div class="stat-item"><strong>۱۲k+</strong><span>مشتری راضی</span></div><div class="stat-item"><strong>۱۵+</strong><span>سال تجربه</span></div><div class="stat-item"><strong>۲۰+</strong><span>روش نوین درمانی</span></div><div class="stat-item"><strong>۹۸٪</strong><span>رضایت بیماران</span></div></div></section>
<section id="services" class="section services-section"><div class="container"><div class="section-heading"><span class="eyebrow">خدمات ما</span><h2>مناسب‌ترین درمان‌ها برای زیبایی طبیعی</h2><p>هر درمان پس از معاینه و مشاوره تخصصی، متناسب با نیاز شما طراحی می‌شود.</p></div><div class="services-grid"><article class="service-card"><div class="icon">✦</div><h3>بلفاروپلاستی</h3><p>رفع پف زیر چشم و جوان‌سازی قفسه چشم با نتیجه طبیعی.</p><a href="<?php echo esc_url(home_url('/خدمات/')); ?>">اطلاعات بیشتر</a></article><article class="service-card"><div class="icon">✦</div><h3>لیفت صورت و گردن</h3><p>سفت‌کردن پوست و بهبود فرم صورت برای ظاهری جوان‌تر.</p><a href="<?php echo esc_url(home_url('/خدمات/')); ?>">اطلاعات بیشتر</a></article><article class="service-card"><div class="icon">✦</div><h3>جراحی بینی</h3><p>اصلاح فرم بینی با حفظ تناسب چهره و تنفس طبیعی.</p><a href="<?php echo esc_url(home_url('/خدمات/')); ?>">اطلاعات بیشتر</a></article><article class="service-card"><div class="icon">✦</div><h3>فیلر و بوتاکس</h3><p>کاهش خطوط و اصلاح فرم صورت با روش‌های کم‌تهاجمی.</p><a href="<?php echo esc_url(home_url('/خدمات/')); ?>">اطلاعات بیشتر</a></article></div></div></section>
<section class="section about-section"><div class="container about-grid"><div class="about-image-wrap"><img src="<?php echo esc_url($img . 'consultation.svg'); ?>" alt="مشاوره تخصصی زیبایی"></div><div class="about-copy"><span class="eyebrow">درباره کلینیک</span><h2>در کنار شما، با تجربه و دقت برای نتیجه‌ای طبیعی.</h2><p>ما با ترکیب تخصص پزشکی، طراحی درمان شخصی و استفاده از فناوری‌های روز، تجربه‌ای امن و شخصی برای هر بیمار خلق می‌کنیم.</p><ul class="check-list"><li>مشاوره دقیق و شخصی‌سازی‌شده</li><li>تکنولوژی مدرن و به‌روز</li><li>پیگیری دقیق بعد از عمل</li><li>تیم پزشکی مجرب و حرفه‌ای</li></ul></div></div></section>
<section class="section showcase-section"><div class="container"><div class="section-heading"><span class="eyebrow">گالری نتایج</span><h2>نمونه‌هایی از نتایج طبیعی ما</h2><p>تصاویر زیر نمونه گرافیکی قالب هستند و با تصاویر مجاز کلینیک قابل جایگزینی‌اند.</p></div><div class="gallery-grid"><div class="gallery-item"><img src="<?php echo esc_url($img . 'before-after-face.svg'); ?>" alt="نمونه قبل و بعد جراحی صورت"></div><div class="gallery-item"><img src="<?php echo esc_url($img . 'before-after-profile.svg'); ?>" alt="نمونه نتیجه طبیعی جراحی زیبایی"></div><div class="gallery-item"><img src="<?php echo esc_url($img . 'patient-care.svg'); ?>" alt="مراقبت از بیمار در کلینیک"></div></div></div></section>
<section class="section team-section"><div class="container"><div class="section-heading"><span class="eyebrow">تیم پزشکی</span><h2>متخصصان مجرب و ماهر</h2></div><div class="team-grid"><article class="team-card"><img src="<?php echo esc_url($img . 'doctor-sara.svg'); ?>" alt="دکتر سارا احمدی"><div class="team-card-body"><h3>دکتر سارا احمدی</h3><p>جراح پلاستیک و زیبایی</p></div></article><article class="team-card"><img src="<?php echo esc_url($img . 'doctor-amir.svg'); ?>" alt="دکتر امیر هاشمی"><div class="team-card-body"><h3>دکتر امیر هاشمی</h3><p>متخصص جراحی صورت</p></div></article><article class="team-card"><img src="<?php echo esc_url($img . 'doctor-sara.svg'); ?>" alt="دکتر نرگس رضایی"><div class="team-card-body"><h3>دکتر نرگس رضایی</h3><p>پزشک زیبایی و پوست</p></div></article></div></div></section>
<section class="section testimonials-section"><div class="container"><div class="section-heading"><span class="eyebrow">تجربه بیماران</span><h2>اعتماد شما، ارزشمندترین نتیجه ماست</h2></div><div class="testimonial-grid"><blockquote class="testimonial-item">«از مشاوره تا نتیجه نهایی، همه چیز دقیق و حرفه‌ای بود.»<footer>— مریم ر.</footer></blockquote><blockquote class="testimonial-item">«تیم متخصص با صبر و حوصله تمام مراحل را همراهی کردند.»<footer>— ندا خ.</footer></blockquote><blockquote class="testimonial-item">«نتیجه‌ای طبیعی گرفتم و از انتخابم کاملاً راضی هستم.»<footer>— الهه م.</footer></blockquote></div></div></section>
<section class="section faq-section"><div class="container faq-wrap"><div class="section-heading"><span class="eyebrow">پرسش‌های متداول</span><h2>قبل از مشاوره چه بدانیم؟</h2></div><div class="faq-list"><details><summary>جلسه مشاوره چگونه انجام می‌شود؟</summary><p>پس از بررسی سوابق و معاینه، گزینه‌های درمانی، زمان بهبودی و هزینه به‌صورت شفاف توضیح داده می‌شود.</p></details><details><summary>آیا نتیجه جراحی طبیعی خواهد بود؟</summary><p>هدف درمان، حفظ تناسب چهره و ایجاد نتیجه طبیعی متناسب با ویژگی‌های هر فرد است.</p></details><details><summary>چطور نوبت رزرو کنم؟</summary><p>فرم پایین صفحه را تکمیل کنید تا کارشناسان کلینیک برای هماهنگی با شما تماس بگیرند.</p></details></div></div></section>
<section id="contact" class="section cta-section"><div class="container cta-box"><div><span class="eyebrow">رزرو مشاوره</span><h2>برای شروع مسیر زیبایی خود با ما صحبت کنید.</h2><p>فرم تماس، تلفن و زمان مناسب خود را برای ما ارسال کنید.</p></div><a href="mailto:info@audubonclinic.com" class="button">درخواست مشاوره</a></div></section>
</main>
<?php get_footer(); ?>
